add8:
	verilator add8.v add8.cpp --cc --exe --build --trace
add4:
	verilator add4.v add4.cpp --cc --exe --build --trace

add32:	
	verilator add32.v add32.cpp --cc --exe --build --trace

sub32:	
	verilator sub32.v sub32.cpp --cc --exe --build --trace


clean:	
	sudo rm -rf obj_dir wave.vcd
