add8:
	verilator add8.v add8.cpp --cc --exe --build --trace
add4:
	verilator add4_full_fast.v add4_full_fast.cpp --cc --exe --build --trace

add32:	
	verilator add32.v add32.cpp --cc --exe --build --trace


clean:	
	sudo rm -rf obj_dir wave.vcd
